### ISSUE TITLE
Error: "Could not connect to remote compilation service"

### ISSUE THREAD

**Issue by justintroutman** [vorple/borogove-ide#1]
Hi! When I attempt to compile either Inform 7 or Inform 7 with Vorple, I'm presented with a "Could not connect to remote compilation service" error. A [past thread I found](https://intfiction.org/t/borogove-online-editor-for-vorple-inform-hugo-and-dialog/43821/40) suggests that this could be due to a server upgrade, but I thought I'd raise the issue in case it's something different. Cheers!

**Comment by juhana** [comment]
The service was indeed down again but should be working now. Thanks for letting me know!
