### ISSUE TITLE
"Parchment does not support Internet Explorer" but I'm not using Internet Explorer

### ISSUE THREAD

**Issue by nullbasis** [vorple/borogove-ide#2]
I'm using the Borogove IDE in SeaMonkey 2.53. This is the browser I use for writing projects, to keep myself from getting distracted by all my bookmarks and such in my regular browser. It works fine for all of the sites I use it for.

I _know_ Parchment supports this browser, because I have no issues on PlayFic. Further, I have no problems compiling, playing, and downloading on Borogove, though I didn't realize at first that I could actually type in commands in the on-site preview since there's a CSS rule being deliberately applied to the cursor to make it invisible, so it _looks_ like I can't do anything.

My browser works just fine, and I'm not even using the browser Borogove thinks I'm using, so can this unnecessary warning banner maybe be removed?

**Comment by juhana** [comment]
Thanks, I've removed the check from Parchment – it's basically unnecessary here because the IDE won't work in Internet Explorer anyway. I'll open a new ticket about the core issue in the Parchment repository.

**Comment by juhana** [comment]
Looking at the Parchment source more carefully, it looks like it's moving to use dynamic module import that SeaMonkey doesn't support yet. SeaMonkey 2.53 corresponds to Firefox 56, but module support is available from Firefox 67 onward. Playfic uses an older version of Parchment that doesn't use modules and Borogove uses a later version that has the IE check in place but doesn't fully use modules yet.

It's likely that Borogove's Parchment version will be updated later but there's no pressure to do that yet. When that happens it'll stop working again unless SeaMonkey gets an update. Also if you only use SeaMonkey to keep it separate from the regular browser, it's also possible to make multiple profiles in Firefox that behave practically the same as different browsers.

**Comment by curiousdannii** [comment]
Yeah sorry, the work in progress Parchment (not yet live on iplayif.com) uses dynamic import, which is [supported nearly everywhere now](https://caniuse.com/es6-module-dynamic-import). I didn't know SeaMonkey was still being produced. ESR releases are also likely to not work. I'll change the error message to be more generic, but at this stage I don't intend to support browsers without dynamic import.

**Comment by nullbasis** [comment]
Well, that's sad to hear. I'll have to bring it up with the SeaMonkey devs.
