### ISSUE TITLE
Sentry Organization Slug Required for Build

### ISSUE THREAD

**Issue by jeffnyman** [vorple/borogove-ide#3]
Maybe this is known or understood but I wanted to call it out just in case. When you try to do the `yarn build` mentioned in the instructions, the following occurs:

```
yarn run v1.22.10
$ REACT_APP_VARIANT=ide node scripts/build.js
Creating an optimized production build...
Failed to compile.

Sentry CLI Plugin: Command failed: /Users/jnyman/Apostle/borogove-ide/node_modules/@sentry/cli/sentry-cli releases new 6154cf633229686028de0c56f5a2f4d2e2427da8
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

error Command failed with exit code 1.
```

My context for these kinds of applications is admittedly weak so maybe this is obvious to someone with knowledge who builds these tools, but should this perhaps be called out that you have to have this "organization slug"? Or, alternatively, is that necessarily required?

It was not even remotely clear how to do this. I went to Sentry.io and had to set myself up. But all the commands given for setting up the organization slug actually led to more problems with the project itself.

Just wanted to surface in case this was an issue. If it's more a user issue (i.e., me not knowing what I'm doing), it's possible others will fall into this as well and may need some guidance.

**Comment by juhana** [comment]
Good find, Sentry is optional so building the app should work even without it. It's now fixed so that the build skips Sentry if it hasn't been cofigured.
